[package]
name = "automation-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
simple_logger = "2.2.0"
rayon = "1.5.3"
